### ISSUE TITLE
Crash If no User Camera

### ISSUE THREAD

**Issue by PhaestusFox** [jakobhellermann/bevy_editor_pls#16]
The Editor will crash the game if you click the screen while you are in editor mode if you have not spawned your own camera, a UI camera does not count(before you say this is a rare edge case). it crashes in at least two separate checks, one in the raycast logic, and once in the change camera selection.

**Comment by jakobhellermann** [comment]
Thanks for the issue, I fixed the panics in https://github.com/jakobhellermann/bevy_editor_pls/commit/cda64e2a7fca3d1f1b15768ad3e1898ab52c1a41
