### ISSUE TITLE
Windows: Can't get fly or orbit cameras to work

### ISSUE THREAD

**Issue by johanhelsing** [jakobhellermann/bevy_editor_pls#3]
Hi :)

How is the fly camera supposed to work?

I tried running the examples and pressing ctrl+f and pressing wasd, arrow keys, holding down mouse etc, but nothing seems to happen to the camera.

This was on windows, fwiw.

I tried both before and after the bump to bevy-inspector-egui 0.6

**Comment by johanhelsing** [comment]
Works fine on my linux setup

**Comment by jakobhellermann** [comment]
Huh, do the examples in https://github.com/mcpar-land/bevy_fly_camera work on windows?

**Comment by johanhelsing** [comment]
> Huh, do the examples in https://github.com/mcpar-land/bevy_fly_camera work on windows?

yep.

I tried your fork, and the 3d example doesn't do anything except print `Toggled FlyCamera enabled!`

**Comment by jakobhellermann** [comment]
Does the repo if the PR https://github.com/mcpar-land/bevy_fly_camera/pull/17 work? If so I'll just switch to that instead of my fork.

**Comment by johanhelsing** [comment]
yep, that one works as well :)

**Comment by jakobhellermann** [comment]
Closing this as orbit camera controls don't yet exist in the redesign.
