### ISSUE TITLE
Panic with 0.10, can't use

### ISSUE THREAD

**Issue by djeedai** [jakobhellermann/bevy_editor_pls#75]
I just tried to add `bevy_editor_pls = "0.4"` but now my app panics at startup 100% of the time:

> thread 'main' panicked at 'alloc::borrow::Cow<str> not registered', C:\Users\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy-inspector-egui-0.18.3\src\inspector_egui_impls\mod.rs:121:28

**Comment by djeedai** [comment]
So I have no idea what happened, but today I tried again and everything works. I'm quite confused, I didn't change anything.

Closing for now, can re-open if that pops back again for me or someone else.

**Comment by zlepper** [comment]
To anyone who encounters this in the future: It seems to happen if the `DefaultPlugins` from bevy is being added to the app _before_ the editor plugin. The solution is the ensure the default plugins are added first.
