### ISSUE TITLE
New-main fails to build

### ISSUE THREAD

**Issue by PROMETHIA-27** [jakobhellermann/bevy_editor_pls#8]
I was looking to try out (and possibly contribute) to this repo but the 0.6 version doesn't build without some modifications, as the current commit depends on a deleted pub-next-widget-position branch of a fork of egui, which from [this issue on egui](https://github.com/emilk/egui/pull/1089) I don't believe is needed anymore. I was able to fix this pretty quickly with the function from that issue, and I assume that's already been done locally, but could that be pushed to the github repo?

**Comment by jakobhellermann** [comment]
Pushed the fix :+1:
