### ISSUE TITLE
Bevy 0.13

### ISSUE THREAD

**Issue by asour8** [jakobhellermann/bevy_editor_pls#95]
Bevy 0.13
![image](https://github.com/jakobhellermann/bevy_editor_pls/assets/52638772/bd7de5f2-345c-4cc7-8f81-b975fd335b33)

**Comment by BD103** [comment]
This is blocked by `bevy-inspector-egui` updating, see https://github.com/jakobhellermann/bevy-inspector-egui/pull/185.

**Comment by asour8** [comment]
fixed by 79602455ec329c4d5d5fada226374157e21d8f38
